# Copyright 2026 Quantova Inc
# SPDX-License-Identifier: Apache-2.0 OR MIT
name: ci

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          path: quantova-cli
          persist-credentials: false
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          repository: Quantova/QCore.rs
          ref: 715c016858bf83ef01bc100b2a0fc2677c39a902
          path: QCore.rs
          persist-credentials: false
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          repository: Quantova/Quantova-Chain
          ref: 469679ff3b935b9ecdd0be0e859525b8e0efa973
          path: Quantova-Chain
          persist-credentials: false
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          repository: Quantova/QVM
          ref: faf4870915c3419fa5e350e3257bfffd1074fe1f
          path: QVM
          persist-credentials: false
      - name: fmt
        working-directory: quantova-cli
        run: cargo fmt --all -- --check
      - name: clippy
        working-directory: quantova-cli
        run: cargo clippy --all-targets --all-features --locked -- -D warnings
      - name: test
        working-directory: quantova-cli
        run: cargo test --all-features --locked
