# Copyright 2026 Quantova Inc
# SPDX-License-Identifier: Apache-2.0 OR MIT
name: ci

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          path: quantova-cli
          persist-credentials: false
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          repository: Quantova/QCore.rs
          ref: 5fbce1f4e23f0d723a202cdfe39599d188e506f2
          path: QCore.rs
          persist-credentials: false
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          repository: Quantova/Quantova-Chain
          ref: 8ceac4f6bf15ab64dab8aff5e24b12c70be8001a
          path: Quantova-Chain
          persist-credentials: false
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          repository: Quantova/QVM
          ref: f2efa4bb143611a58a94607b8d10fdafc69c372c
          path: QVM
          persist-credentials: false
      - name: fmt
        working-directory: quantova-cli
        run: cargo fmt --all -- --check
      - name: clippy
        working-directory: quantova-cli
        run: cargo clippy --all-targets --all-features --locked -- -D warnings
      - name: test
        working-directory: quantova-cli
        run: cargo test --all-features --locked
      - name: deny
        working-directory: quantova-cli
        run: |
          cargo install cargo-deny --locked --version 0.16.3
          cargo deny check bans licenses sources advisories
