# Copyright 2026 Quantova Inc
# SPDX-License-Identifier: Apache-2.0 OR MIT
name: ci

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          path: quantova-cli
          persist-credentials: false
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          repository: Quantova/QCore.rs
          ref: 866a837bb7ebba6e8840eee753023a2dceac2c87
          path: QCore.rs
          persist-credentials: false
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          repository: Quantova/Quantova-Chain
          ref: f0b0c3c0931b9b512def908b52b5ba80043256a8
          path: Quantova-Chain
          persist-credentials: false
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          repository: Quantova/QVM
          ref: 62fadd4ced98c4c4eb5042391aba54dabac51431
          path: QVM
          persist-credentials: false
      - name: fmt
        working-directory: quantova-cli
        run: cargo fmt --all -- --check
      - name: clippy
        working-directory: quantova-cli
        run: cargo clippy --all-targets --all-features --locked -- -D warnings
      - name: test
        working-directory: quantova-cli
        run: cargo test --all-features --locked
